<?php

/**
 * This file is part of Milpa Agent — long-running coding sessions for the Milpa PHP framework.
 *
 * (c) Rodrigo Vicente - TeamX Agency — https://teamx.agency <hola@teamx.agency>
 *
 * @license Apache-2.0
 *
 * @link    https://github.com/getmilpa/agent
 */

declare(strict_types=1);

namespace Milpa\Agent\Tests;

use Milpa\Agent\Compactor;
use Milpa\Agent\SessionStore;
use Milpa\Agent\Tests\Support\GoldenSessionFixture;
use Milpa\EventStore\InMemoryEventStore;
use PHPUnit\Framework\TestCase;

/**
 * ACCEPTANCE (b), AND THE CONTROL OF THE WHOLE SLICE: no budget declared, no byte moves.
 *
 * The golden file was generated by running THE CODE AS IT WAS before the budget existed against
 * the same deterministic fixture. If any assertion here fails, the slice changed what an
 * unbudgeted session sends to the model — and containing the context of budgeted sessions was
 * never a licence to touch anyone else's window.
 */
final class NullBudgetGoldenTest extends TestCase
{
    private const GOLDEN = __DIR__ . '/Fixtures/null-budget-window.golden.json';

    /** @return array{store: SessionStore, id: string} */
    private function compactedFixture(): array
    {
        $store = new SessionStore(new InMemoryEventStore());
        $id = GoldenSessionFixture::build($store);
        $session = $store->load($id) ?? self::fail('fixture session did not load');
        self::assertNotNull(
            (new Compactor(maxTurns: 20, keepRecent: 5))->compactIfNeeded($store, $session),
            'the fixture must actually compact, or the summary path goes unmeasured',
        );

        return ['store' => $store, 'id' => $id];
    }

    public function testTheNullBudgetWindowIsByteIdenticalToTheGolden(): void
    {
        ['store' => $store, 'id' => $id] = $this->compactedFixture();
        $after = $store->load($id) ?? self::fail('compacted session did not load');

        $golden = json_decode((string) file_get_contents(self::GOLDEN), true, flags: \JSON_THROW_ON_ERROR);
        self::assertIsArray($golden);

        $actual = [
            'window' => $after->window(),
            'classifiedWindow' => $after->classifiedWindow(),
            'summary' => $after->summary,
            'briefing' => $after->stateBriefing(),
        ];

        self::assertSame($golden, $actual, 'null budget must compose byte-for-byte what today composes');

        // Belt and braces: the same bytes, not merely the same decoded values.
        self::assertSame(
            (string) file_get_contents(self::GOLDEN),
            json_encode($actual, \JSON_PRETTY_PRINT | \JSON_UNESCAPED_UNICODE | \JSON_UNESCAPED_SLASHES | \JSON_THROW_ON_ERROR) . "\n",
        );
    }

    /** Omitting the argument entirely is the same contract as passing null. */
    public function testTheDefaultArgumentIsTheNullBudget(): void
    {
        ['store' => $store, 'id' => $id] = $this->compactedFixture();
        $after = $store->load($id) ?? self::fail('compacted session did not load');

        self::assertSame($after->window(), $after->window(null));
        self::assertSame($after->classifiedWindow(), $after->classifiedWindow(null));
        self::assertSame($after->stateBriefing(), $after->stateBriefing(null));
    }
}
